name: mini_ide
description: A mini-ide that can be added to other Flutter apps.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0-417.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
